#!/bin/bash

yay -S --needed \
  alacritty \
  inotify-tools \
  base-devel \
  pkgfile \
  git \
  ranger \
  neofetch \
  zsh \
  tldr \
  fzf \
  curl \
  htop \
  fd \
  ripgrep \
  bat \
  lsd \
  eza \
  neovim \
  ttf-jetbrains-mono-nerd \
  fzf \
  tmux \
  lazygit \
  net-tools \
  brave \
  samba \
  avahi \
  coppwr \
  btop \
  ttf-sourcecodepro-nerd