#!/bin/bash

# ---------------------------------------------------------------------------
# This script should install programs listed on file 'install-programs'
# ---------------------------------------------------------------------------
# My Variables
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROGRAMS_FILE=$1

[ -z "$1" ] && echo "usage: $0 [file with program names]" && exit 1

FILE_PATH=$(realpath $PROGRAMS_FILE)
LOG_FILE="$SCRIPT_DIR/install.log"

echo "---------------------------------------------------------------------------" | tee -a "$LOG_FILE"
echo "    Installation started at $(date)" | tee -a "$LOG_FILE"
echo "---------------------------------------------------------------------------" | tee -a "$LOG_FILE"

echo "This program will attempt to install all these programs:"

echo -e "$BRIGHT_GREEN"
bat $FILE_PATH
echo -e "$RESET"

# read -p "Installation will proceed without further confirmations. Do you want to continue?(Y/n) " user_input
# [[ "$user_input" != "y" ]] && [[ "$user_input" != "Y" ]] && echo "Exiting program" && exit 0

# ---------------------------------------------------------------------------
# Suported installers
# ---------------------------------------------------------------------------
INSTALLERS=(
	"pacman"
	"apt"
)

# ---------------------------------------------------------------------------
# Declaring an associative array so i can store used flags for each installer
# ---------------------------------------------------------------------------
declare -A INSTALLERS_FLAGS

INSTALLERS_FLAGS["pacman"]="-S --noconfirm"
INSTALLERS_FLAGS["apt"]="install" #apt

# ---------------------------------------------------------------------------
# Find which installer is available
# ---------------------------------------------------------------------------
for option in "${INSTALLERS[@]}"; do
	if command -v "$option" &>/dev/null; then
		INSTALLER=$option
		break
	fi
done
FLAGS="${INSTALLERS_FLAGS[$option]}"

if [ $INSTALLER eq "$pacman" ]; then
	$INSTALLER -Syu
fi

# ---------------------------------------------------------------------------
# Iterate through programs and install
# ---------------------------------------------------------------------------
if [ -f $FILE_PATH ]; then
	while IFS= read -r line; do
		program=$(echo "$line" | sed 's/#.*//' | xargs)

		echo -e "\n\tInstalling $program...\n"

		if sudo $INSTALLER $FLAGS "$program" &>/dev/null; then
			echo -e "$BRIGHT_GREEN\t$program installed successfully$RESET" | tee -a "$LOG_FILE"
		else
			echo -e "$BRIGHT_RED\tFailed to install $program$RESET" | tee -a "$LOG_FILE"
		fi

	done <"$PROGRAMS_FILE"
else
	echo "File $BRIGHT_RED'$PROGRAMS_FILE' not found"
fi
# ---------------------------------------------------------------------------
#
echo "---------------------------------------------------------------------------" | tee -a "$LOG_FILE"
echo "     Installation ended at $(date)" | tee -a "$LOG_FILE"
echo "---------------------------------------------------------------------------" | tee -a "$LOG_FILE"
