#!/bin/bash

brew install \
  bat \
  fzf \
  tmux \
  lsd \
  nvim \
  lazygit \
  gh \
  font-jetbrains-mono-nerd-font \
  yazi \
  fd \
  ripgrep \
  ffmpeg \
  sevenzip \
  jq \
  poppler \
  fd \
  ripgrep \
  fzf \
  zoxide \
  imagemagick \
  font-symbols-only-nerd-font

alacritty