#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Create an array with my link pairs
configs=(
  # "$I3_HOME/configs/i3.config $HOME/.config/i3/config"
  # "$I3_HOME/configs/i3blocks.config $HOME/.config/i3blocks/config"
  "$SCRIPT_DIR/configs/zshrc $HOME/.zshrc"
  "$SCRIPT_DIR/configs/gitconfig $HOME/.gitconfig"
  "$SCRIPT_DIR/configs/rc.conf $HOME/.config/ranger/rc.conf"
  "$SCRIPT_DIR/configs/kitty $HOME/.config/kitty/kitty.conf"
  "$SCRIPT_DIR/configs/hyprland $HOME/.config/hypr/hyprland.conf"
  "$SCRIPT_DIR/configs/aliases $HOME/.aliases"
  "$SCRIPT_DIR/configs/colors $HOME/.colors"
  "$SCRIPT_DIR/configs/vimrc $HOME/.vimrc"
)

# Iterate through that array and pass pair to the script
# Seeing as my script takes in the pair in the same format written above,
# no parsing is necessary
echo ""

for pair in "${configs[@]}"; do
  sh $SCRIPT_DIR/scripts/link-files $pair
done
