#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ ! -d $HOME/.config/alacritty ]; then
  mkdir -p $HOME/.config/alacritty
fi

# Create an array with my link pairs
configs=(
  "$HOME/dotfiles/rc.conf $HOME/.config/ranger/"
  "$HOME/dotfiles/nvim $HOME/.config/"
  "$HOME/dotfiles/.zshrc $HOME/.zshrc"
  "$HOME/dotfiles/alacritty.toml $HOME/.config/alacritty/"
)

# Iterate through that array and pass pair to the script
# Seeing as my script takes in the pair in the same format written above,
# no parsing is necessary
echo ""

for pair in "${configs[@]}"; do
  sh $SCRIPT_DIR/scripts/link-files.sh $pair
done