#!/bin/bash

export I3_HOME=$(pwd)

source ./configs/colors

$I3_HOME/install-configs
$I3_HOME/programs/install-programs

# if command -v notify-send; then
# notify-send "User Config" "User environment updated"
# fi
