#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

sh $SCRIPT_DIR/scripts/programs/hypr-programs

# Create an array with my link pairs
configs=(
  "$HOME/dotfiles/hypr/* $HOME/.config/hypr/"
  "$HOME/dotfiles/waybar/windows $HOME/.config/waybar"
)

echo ""

for pair in "${configs[@]}"; do
  sh $SCRIPT_DIR/scripts/link-files.sh $pair
done
