#!/bin/bash

configs=(
  "$I3_HOME/configs/i3.config $HOME/.config/i3/config"
  "$I3_HOME/configs/rc.conf $HOME/.config/ranger/rc.conf"
  "$I3_HOME/configs/zshrc $HOME/.zshrc"
  "$I3_HOME/configs/aliases $HOME/.aliases"
  "$I3_HOME/configs/colors $HOME/.colors"
)

for pair in "${configs[@]}"; do
  sh $I3_HOME/link-files $pair
done

source $HOME/.zshrc
