#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Create an array with my link pairs
configs=(
  "$HOME/dotfiles/.gitconfig $HOME/.gitconfig"
  "$HOME/dotfiles/.aliases.sh $HOME/.aliases"
)

# Iterate through that array and pass pair to the script
# Seeing as my script takes in the pair in the same format written above,
# no parsing is necessary
echo ""

for pair in "${configs[@]}"; do
  sh $SCRIPT_DIR/scripts/link-files.sh $pair
done