#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mkdir -p ~/.config/tmux

sh $SCRIPT_DIR/scripts/link-files.sh $HOME/dotfiles/tmux.conf $HOME/.config/tmux/tmux.conf

if [ -d ${HOME}/.tmux/plugins/tpm ]; then
  echo "tpm already installed"
else
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi
