#!/bin/bash

# ORIGIN_PATH = $1
# DESTINATION_PATH = $2

if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Error: paths not specified"
  echo "Usage: link-files path/to/origin path/to/destination"
  exit 1
fi

if [ ! -f $1 ]; then
  echo "file $1 not found"
  exit 1
fi

ORIGIN_PATH=$(realpath $1) >/dev/null
IS_LINK=$(readlink $2)

if [ "$IS_LINK" = "$ORIGIN_PATH" ]; then
  echo "\n\tPath --> $BRIGHT_GREEN$1$RESET is already a link to $BRIGHT_GREEN$2$RESET\n"
  exit 0
fi

echo "\n\tLink --> $BRIGHT_GREEN$ORIGIN_PATH$RESET to ==> $BLINK$BRIGHT_BLUE$2$RESET created sucessfully\n"
ln -sf $ORIGIN_PATH $2
