#!/bin/bash

# Install oh my zsh ----------------------------------------------

echo -e ""

# ------------------------------------------------------------------------------
if [ -d ${ZSH}/custom/plugins/zsh-autosuggestions ]; then
  echo -e "$BRIGHT_YELLOW\tzsh-autosuggestions already installed\t$RESET"
else
  echo -e "$BRIGHT_GREEN\tInstalling zsh-autosuggestions\t$RESET"
  git clone --depth 1 -- https://github.com/zsh-users/zsh-autosuggestions \
    ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
fi

# ------------------------------------------------------------------------------
if [ -d ${ZSH}/custom/plugins/F-Sy-H ]; then
  echo -e "$BRIGHT_YELLOW\tF-Sy-H already installed\t$RESET"
else
  echo -e "$BRIGHT_GREEN\tInstalling F-Sy-H (Fast syntax highlight by dharma)\t$RESET"
  git clone --depth 1 -- https://github.com/z-shell/F-Sy-H.git \
    ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/F-Sy-H
fi

# ------------------------------------------------------------------------------
if [ -d $ZSH/custom/plugins/zsh-autocomplete ]; then
  echo -e "$BRIGHT_YELLOW\tzsh-autocomplete already installed\t$RESET"
else
  echo -e "$BRIGHT_GREEN\tInstalling zsh-autocomplete\t$RESET"
fi

# ------------------------------------------------------------------------------
if [ -d ${ZSH}/custom/plugins/zsh-completions ]; then
  echo -e "$BRIGHT_YELLOW\tzsh-completions already installed\t$RESET"
else
  echo -e "$BRIGHT_GREEN\tInstalling zsh-completions\t$RESET"
  git clone --depth 1 -- https://github.com/zsh-users/zsh-completions \
    ${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions
fi

# ------------------------------------------------------------------------------
if [ -d ${ZSH}/custom/plugins/zsh-vi-mode ]; then
  echo -e "$BRIGHT_YELLOW\tzsh-vi-mode already installed\t$RESET"
else
  echo -e "$BRIGHT_GREEN\tInstalling zsh-vi-mode\t$RESET"
  git clone https://github.com/jeffreytse/zsh-vi-mode \
    $ZSH_CUSTOM/plugins/zsh-vi-mode
fi

if [ -f $HOME/.zshrc.pre-oh-my-zsh ]; then
  rm $HOME/.zshrc
  mv $HOME/.zshrc.pre-oh-my-zsh $HOME/.zshrc
fi

echo ""

#-------

if [ ! -d $HOME/bin ]; then 
  mkdir $HOME/bin
fi

if [ ! -f $HOME/bin/oh-my-posh ]; then 
  curl -s https://ohmyposh.dev/install.sh | bash -s -- -d ~/bin
else
  echo -e "\tOh-my-posh is arealdy install in $HOME/bin"
fi


# Missing ---
# zsh-autocomplete
# add:
#   cd to repo -> pull
# to update plugin