#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$(find \
    ~/workhub \
    ~/github \
    ~/dotfiles \
    ~/i3life \
    -mindepth 0 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
  exit 0
fi

session_name=$(tmux display-message -p "#S")
selected_name=$(basename $selected)

# Run tmux  on selected name if tmux is not running
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -c $selected
  exit 0
fi

if ! tmux has-session -t=$session_name:$selected_name 2>/dev/null; then
  tmux neww -dn $selected_name -c $selected
fi

tmux -2 select-window -t $session_name:$selected_name