#!/bin/bash

# This script should install programs listed on file 'install-programs'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROGRAMS_FILE="$SCRIPT_DIR/program-names"

FILE_PATH=$(realpath $PROGRAMS_FILE)

if [ -f $FILE_PATH ]; then

  while IFS= read -r program_name; do

    command=$(echo "$program_name" | cut -d " " -f 1)
    lib=$(echo "$program_name" | cut -d " " -f 2)

    if ! command -v "$command" &>/dev/null; then
      echo -e "\n$BRIGHT_GREEN\tInstalling $lib$RESET...\n"
      sudo apt install -y "$lib"
    else
      echo -e "\t$BRIGHT_RED$lib$RESET is already installed on this system"
    fi

  done <"$PROGRAMS_FILE"

else
  echo "File $BRIGHT_RED'$PROGRAMS_FILE' not found"
fi
